name: urbandictionary
version: 0.1.0
description: Urban Dictionary API clients for accessing word definitions

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  pedantic: ^1.9.2
  dio: ^3.0.9
  json_annotation: ^3.0.1

dev_dependencies:
  build_runner: ^1.10.0
  json_serializable: ^3.3.0